name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: catkin
      cmakeInstallationPath: catkin-installation
      tagName: 0.8.10
      targetZip: catkin-${{ github.ref_name }}.zip
    steps:
      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/ros/catkin.git && cd catkin && git checkout ${{ env.tagName }}
      
      - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        shell: cmd
        run: |
          curl https://github.com/2641797006/c/blob/master/GCC-zip/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z?raw=true -L --output x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z &&^
          dir &&^
          7z.exe x x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
          
      - name: curl python-3.7.9-amd64-portable.zip
        shell: cmd
        run: |
          curl https://github.com/dirkarnez/python-portable/releases/download/v3.8.10/python-3.8.10-amd64-portable.zip -L --output python-3.8.10-amd64-portable.zip &&^
          dir &&^
          7z.exe x python-3.8.10-amd64-portable.zip -o"python-3.8.10-amd64-portable"
          
      - name: curl cmake-3.24.0-windows-x86_64.zip
        shell: cmd
        run: cd /d ${{ github.workspace }} && curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip && dir && 7z.exe x cmake-3.24.0-windows-x86_64.zip
      
      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run: cd /d ${{ github.workspace }} && curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe && dir && 7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"PortableGit-2.38.1-64-bit"
        
#         #             -DEMPY_SCRIPT="%CD_LINUX%/empy/em.py" ^
#       - shell: cmd
#         run: |
#           curl https://files.pythonhosted.org/packages/3b/95/88ed47cb7da88569a78b7d6fb9420298df7e99997810c844a924d96d3c08/empy-3.3.4.tar.gz -L --output empy-3.3.4.tar.gz &&^
#           tar -xvf empy-3.3.4.tar.gz &&^
#           rename empy-3.3.4 empy &&^
#           cd empy &&^
#           dir
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
            set PATH=^
            ${{ github.workspace }}\mingw64;^
            ${{ github.workspace }}\mingw64\bin;^
            ${{ github.workspace }}\PortableGit-2.38.1-64-bit\bin;^
            ${{ github.workspace }}\cmake-3.24.0-windows-x86_64\bin;^
            ${{ github.workspace }}\python-3.8.10-amd64-portable;^
            ${{ github.workspace }}\python-3.8.10-amd64-portable\Scripts;
            gcc --version &&^
            set CD_LINUX=%CD:\=/%
            cd catkin &&^
            python -m pip install --upgrade pip &&^
            python -m pip install empy &&^
            cmake.exe -G "MinGW Makefiles" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCATKIN_ENABLE_TESTING=OFF ^
            -DCMAKE_INSTALL_PREFIX="cmake-build/${{ env.cmakeInstallationPath }}" -B./cmake-build &&^
            cd cmake-build && cmake --build . && cmake --install . 
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "catkin/cmake-build/${{ env.cmakeInstallationPath }}"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "catkin/cmake-build/${{ env.cmakeInstallationPath }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
